import type { AppProps } from 'next/app';
import Head from 'next/head';

import '@styles/globals.css';

import { SharedHBOStateProvider as Provider } from '@store/HBOProvider';

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<Provider>
			<Head>
				<meta charSet='UTF-8' />
				<meta httpEquiv='X-UA-Compatible' content='IE=edge' />
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<link rel='icon' href='/favicon.ico' />
				<meta name='description' content='Generated by create next app' />
				<title>HBO Clone</title>
			</Head>
			<Component {...pageProps} />
		</Provider>
	);
}

export default MyApp;
