export const SET_USER = 'SET_USER';
export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const TOGGLE_ACCOUNT_MODEL_DISPLAY = 'TOGGLE_ACCOUNT_MODEL_DISPLAY';
export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV';
export const TOGGLE_SEARCH_MODAL = 'TOGGLE_SEARCH_MODAL';

export const ADD_ITEM_TO_WATCH_LIST = 'ADD_ITEM_TO_WATCH_LIST';
export const REMOVE_ITEM_FROM_WATCH_LIST = 'REMOVE_ITEM_FROM_WATCH_LIST';

// enum types {
// 	ADD_USER = 'ADD_USER',
// 	REMOVE_USER = 'REMOVE_USER',
// }
